User:
  properties:
    firstName:
      - NotBlank: ~
      - Length:
          min: 5
    lastName:
      - NotBlank: ~
      - Length:
          min: 3
    age:
      - GreaterThanOrEqual:
          value: 18
