# J'ajoute ici aussi la notion de groups pour que vous voyez comment
# ca peut fonctionner aussi en YAML

# User:
#   properties:
#     firstName:
#       - NotBlank:
#           groups: ['identity']
#       - Length:
#           min: 5
#           groups: ['identity']
#     lastName:
#       - NotBlank:
#           groups: ['identity']
#       - Length:
#           min: 3
#           groups: ['identity']
#     age:
#       - GreaterThanOrEqual:
#           value: 18
